Settings:
  # List of worlds where Auction can not be used.
  # [*] Case sensetive!
  Disabled_Worlds:
  - another_world
  - custom_world
  # Players can not add items to the Auction in the following gamemodes.
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/GameMode.html
  Disabled_Gamemodes:
  - CREATIVE
  # When enabled, players will receive a message about unclaimed listings when they join the server.
  Notify_Unclaimed_On_Join: true
  # When enabled, players will receive a message about expired listings when they join the server.
  Notify_Expired_On_Join: true
  Listings:
    # When enabled, will hide item attributes (damage, durability, etc.) of auction listings.
    Hide_Attributes: false
    # Sets how long items remain in the Auction before being removed if they are not bought within that time.
    # Players can return expired items in the Auction GUI during a limited amount of time (see Purge_In).
    # [*] This setting will not affect existing listings.
    # [Default is 604800 aka 7 days]
    Expire_In: 604800
    # Sets the time (in seconds) for expired and unclaimed items to be completely removed.
    # Players can claim and return expired items in the Auction GUI.
    # [*] This setting will not affect existing listings.
    # [Default is 604800 aka 7 days]
    Purge_In: 604800
    # Sets whether or not a broadcast message will be sent when player adds new listing on the Auction.
    Announce: true
    # Sets max possible amount of active listings for players depends on their rank or permissions.
    # Use '-1' for unlimited amount.
    Listings_Per_Rank:
      # Available values: RANK, PERMISSION
      # ==================== RANK MODE ====================
      # Get value by player's permission group. All keys in 'Values' list will represent permission group names.
      # If player has none of specified groups, the 'Default_Value' setting will be used then
      #   Values:
      #     vip: 1 # -> Player must be in 'vip' permission group.
      #     gold: 2 # -> Player must be in 'gold' permission group.
      #     emerald: 3 # -> Player must be in 'emerald' permission group.
      #
      # ==================== PERMISSION MODE ====================
      # Get value by player's permissions. All keys in 'Values' list will represent postfixes for the 'Permission_Prefix' setting (see below).
      # If player has none of specified permissions, the 'Default_Value' setting will be used then
      #   Permission_Prefix: 'example.prefix.'
      #   Values:
      #     vip: 1 # -> Player must have 'example.prefix.vip' permission.
      #     gold: 2 # -> Player must have 'example.prefix.gold' permission.
      #     emerald: 3 # -> Player must have 'example.prefix.emerald' permission.
      Mode: RANK
      # Sets permission prefix for the 'PERMISSION' mode.
      Permission_Prefix: auction.listings.amount.
      Default_Value: 10
      Values:
        vip: 15
        gold: 20
        admin: -1
    # Sets whether or sold listings are auto-claimed when seller is online.
    AutoClaim: false
    Price:
      # When 'true', removes decimals from listing's price on sell.
      Round_To_Integer: false
      # Sets min. and max. possible listing price for specified currencies.
      # Use '-1' for unlimited amount.
      # Use 'default' keyword to define price range for all unlisted currencies.
      # If listing's currency is not listed here and 'default' value is not defined, no limits will be used!
      Per_Currency:
        vault:
          Min: 1.0
          Max: 1.0E7
        default:
          Min: -1.0
          Max: -1.0
      # Sets min. and max. possible listing price for specified blocks/items.
      # Use '-1' for unlimited amount.
      # Item / Block Names: https://minecraft.wiki/w/Java_Edition_data_values -> Blocks / Items -> Resource location column.
      Per_Material:
        dirt:
          Min: 1.0
          Max: 15.0
        emerald:
          Min: 300.0
          Max: -1.0
        diamond:
          Min: 500.0
          Max: -1.0
    Tax:
      # Tax amount (in % of the listing price) the seller have to pay to add an item on the Auction.
      # Example: Player wants to sell an item for $50, with 10% tax amount he will have to pay $5 to do that.
      On_Listing_Add: 10.0
      # Tax amount (in % of the listing price) that is deducted from the final price when sold listing is claimed.
      # Example: Player sold item for $50, with 10% tax amount he will claim only $45.
      On_Listing_Purchase: 0.0
    # List of items that can not be added as shop products.
    # Vanilla Names: https://minecraft.wiki/w/Java_Edition_data_values -> Blocks / Items -> Resource location column.
    # Supported Plugins: ExcellentCrates, ExecutableItems, ItemsAdder, MMOItems, Nexo, Oraxen
    Disabled_Materials:
    - barrier
    - bedrock
    - flame_sword
    - custom_item_name
    # Items containing the following text in their names can not be added to the Auction.
    Disabled_Names:
    - bad text
    - badword
    # Items containing the following text in their lore can not be added to the Auction.
    Disabled_Lores:
    - bad text line
    - badword
    # List of item's model data values to be disabled from adding in Auction.
    Disabled_Models:
      DIAMOND_HELMET: 1002,1016
      NETHERITE_SWORD: 1001,1015
Menu:
  # Controls whether Auction GUI should re-open on purchase instead of closing.
  ReOpen_On_Purchase: true
  Container_Preview:
    # Sets whether or not container preview feature is available in Auction GUI.
    # This allows players to see content of Shulker Boxes, Chests, Barrels, etc. before purchase.
    # Uses Right Mouse Button (RMB).
    Enabled: true
    # Sets title for the Preview GUI.
    Title: Preview
Database:
  # Sets database type.
  # Available values: MYSQL,SQLITE
  Type: SQLITE
  # Sets how often (in seconds) plugin data will be fetched and loaded from the remote database.
  # Useless for SQLITE.
  # Set to '-1' to disable.
  Sync_Interval: -1
  # This property controls the maximum lifetime of a connection in the pool.
  # A value of 0 indicates no maximum lifetime (infinite lifetime).
  # [The minimum allowed value is 30000ms (30 seconds)]
  # [Default is 1800000 (30 minutes)]
  Max_Lifetime: 1800000
  # Custom prefix for plugin tables in database.
  Table_Prefix: excellentshop_auction
  MySQL:
    # Database user name.
    Username: root
    # Database password.
    Password: ''
    # Database host. Example: localhost:3306, 127.0.0.1:3306
    Host: localhost:3306
    # Name of the MySQL database where plugin will create tables.
    Database: minecraft
    # Connection options. Do not touch unless you know what you're doing.
    Options: ?allowPublicKeyRetrieval=true&useSSL=false
  SQLite:
    # File name for the SQLite database file.
    # Actually it's a path to the file, so you can use directories here.
    FileName: data.db
  Purge:
    # Enables the purge feature.
    # Purge will remove all records from the plugin tables that are 'old' enough.
    Enabled: false
    # Sets maximal 'age' for the database records before they will be purged.
    # This option may have different behavior depends on the plugin.
    # By default it's days of inactivity for the plugin users.
    For_Period: 60
